"""
xer - MMS BER <-> APER codec
Encoding format conversion for IEC 61850 / DL/T 8211 protocol

CLI usage:
    python origin.py --ber-to-aper <hex> --asn <asn_file>
    python origin.py --aper-to-ber <hex> --asn <asn_file>

Library usage:
    from xer import aper_to_ber, ber_to_aper
    ber_bytes = aper_to_ber(aper_bytes)
    aper_bytes = ber_to_aper(ber_bytes)
"""

from pycrate_asn1c.asnproc import compile_text, generate_modules
from pycrate_asn1c.generator import PycrateGenerator
import importlib.util
import argparse
import sys
import os

__all__ = [
    "compile_asn",
    "generate_runtime",
    "load_runtime_module",
    "aper_to_ber",
    "ber_to_aper",
    "example1",
    "example2",
    "get_aper",
    "get_ber",
]

# ──────────────────────────────────────────────────────────────────────────────
# Core API
# ──────────────────────────────────────────────────────────────────────────────

req = None

def compile_asn(asn_file: str) -> str:
    """Read and compile ASN.1 text from file"""
    with open(asn_file, 'r', encoding='utf-8') as f:
        asn1_text = f.read()
    compile_text(asn1_text, filenames=[asn_file])
    return asn1_text


def generate_runtime(output_file: str):
    """Generate Python runtime code from compiled ASN.1"""
    generate_modules(PycrateGenerator, output_file)


def load_runtime_module(output_file: str):
    """Load the generated Python module dynamically"""
    global req
    spec = importlib.util.spec_from_file_location("mms_rt", output_file)
    mms_rt = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mms_rt)
    req = mms_rt.ASN1.MMSpdu

def init(asn_file: str, output_file: str):
    """Init codec - compile ASN once, then load runtime"""
    if not os.path.exists(output_file):
        # First time: compile ASN and generate runtime
        compile_asn(asn_file)
        generate_runtime(output_file)
    load_runtime_module(output_file)

def aper_to_ber(aper_data: bytes) -> bytes:
    """
    APER (Aligned PER) -> BER conversion

    Purpose: Convert APER data captured from network to BER format,
    then feed to 61850bean (Java) for decoding

    Args:
        aper_data: Raw bytes encoded in APER format

    Returns:
        Bytes encoded in BER format
    """
    assert req is not None
    req.from_aper(aper_data)
    return req.to_ber()


def ber_to_aper(ber_data: bytes) -> bytes:
    """
    BER -> APER (Aligned PER) conversion

    Purpose: Convert BER data generated by Java to APER format,
    then send to network

    Args:
        ber_data: Bytes encoded in BER format

    Returns:
        Bytes encoded in APER format
    """
    assert req is not None
    req.from_ber(ber_data)
    return req.to_aper()


# ──────────────────────────────────────────────────────────────────────────────
# Test Examples
# ──────────────────────────────────────────────────────────────────────────────

def example1():
    """Example 1: Construct a Read-Request PDU with test data"""
    req.set_val((
        'confirmed-RequestPDU',
        {
            'invokeID': 123,
            'service': (
                'read',
                {
                    'variableAccessSpecification': (
                        'listOfVariable',
                        [{
                            'variableSpecification': (
                                'name',
                                ('domain-specific', {'domainID': 'TEST', 'itemID': 'VAL1'})
                            )
                        }]
                    )
                }
            )
        }
    ))


def example2():
    """Example 2: GetVariableAccessAttributes request"""
    req.set_val((
        'confirmed-RequestPDU',
        {
            'invokeID': 111,
            'service': (
                'getVariableAccessAttributes',
                ('name', ('domain-specific', {'domainID': 'TEST', 'itemID': 'VAL1'}))
            )
        }
    ))


def get_aper() -> bytes:
    """Get current PDU as APER bytes"""
    return req.to_aper()


def get_ber() -> bytes:
    """Get current PDU as BER bytes"""
    return req.to_ber()


# ──────────────────────────────────────────────────────────────────────────────
# CLI entry point
# ──────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="xer - MMS BER <-> APER codec"
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--ber-to-aper", metavar="HEX",
                       help="Convert BER hex to APER hex")
    group.add_argument("--aper-to-ber", metavar="HEX",
                       help="Convert APER hex to BER hex")
    parser.add_argument("--asn", metavar="PATH",
                       help="ASN.1 file path (compile if provided, else load existing)")
    parser.add_argument("--rt", metavar="PATH",
                       help="Runtime module path (default: <asn_dir>/mms_rt.py)")

    args = parser.parse_args()

    # Resolve paths
    if args.asn:
        asn_path = args.asn
        if not os.path.isabs(asn_path):
            asn_path = os.path.abspath(asn_path)
        rt_path = os.path.join(os.path.dirname(asn_path), "mms_rt.py")
    elif args.rt:
        rt_path = args.rt
        if not os.path.isabs(rt_path):
            rt_path = os.path.abspath(rt_path)
        asn_path = None
    else:
        # Try default location: ./mms_rt.py or ../asn/mms_rt.py
        default_rt = os.path.join(os.getcwd(), "mms_rt.py")
        default_rt2 = os.path.join(os.path.dirname(os.getcwd()), "asn", "mms_rt.py")
        if os.path.exists(default_rt):
            rt_path = default_rt
        elif os.path.exists(default_rt2):
            rt_path = default_rt2
        else:
            parser.error("No --asn or --rt provided, and mms_rt.py not found in default locations")
        asn_path = None

    # Init codec
    if asn_path:
        init(asn_path, rt_path)
    else:
        load_runtime_module(rt_path)

    # Convert
    if args.ber_to_aper:
        data = bytes.fromhex(args.ber_to_aper)
        result = ber_to_aper(data)
        print(result.hex())
    else:
        data = bytes.fromhex(args.aper_to_ber)
        result = aper_to_ber(data)
        print(result.hex())


if __name__ == "__main__":
    main()