"""
xer - MMS BER <-> APER codec
Encoding format conversion for IEC 61850 / DL/T 8211 protocol

Usage:
    from xer import aper_to_ber, ber_to_aper

    ber_bytes = aper_to_ber(aper_bytes)   # APER -> BER
    aper_bytes = ber_to_aper(ber_bytes)   # BER -> APER
"""

from pycrate_asn1c.asnproc import compile_text, generate_modules
from pycrate_asn1c.generator import PycrateGenerator
import importlib.util

__all__ = [
    "compile_asn",
    "generate_runtime",
    "load_runtime_module",
    "aper_to_ber",
    "ber_to_aper",
    "example1",
    "example2",
    "get_aper",
    "get_ber",
]

# ──────────────────────────────────────────────────────────────────────────────
# Core API
# ──────────────────────────────────────────────────────────────────────────────

req = None

def compile_asn(asn_file: str) -> str:
    """Read and compile ASN.1 text from file"""
    with open(asn_file, 'r', encoding='utf-8') as f:
        asn1_text = f.read()
    compile_text(asn1_text, filenames=[asn_file])
    return asn1_text


def generate_runtime(output_file: str):
    """Generate Python runtime code from compiled ASN.1"""
    generate_modules(PycrateGenerator, output_file)


def load_runtime_module(output_file: str):
    """Load the generated Python module dynamically"""
    global req
    spec = importlib.util.spec_from_file_location("mms_rt", output_file)
    mms_rt = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mms_rt)
    req = mms_rt.ASN1.MMSpdu

def init(asn_file: str, output_file: str):
    compile_asn(asn_file)
    generate_runtime(output_file)
    load_runtime_module(output_file)

def aper_to_ber(aper_data: bytes) -> bytes:
    """
    APER (Aligned PER) -> BER conversion

    Purpose: Convert APER data captured from network to BER format,
    then feed to 61850bean (Java) for decoding

    Args:
        aper_data: Raw bytes encoded in APER format

    Returns:
        Bytes encoded in BER format
    """
    assert req is not None
    req.from_aper(aper_data)
    return req.to_ber()


def ber_to_aper(ber_data: bytes) -> bytes:
    """
    BER -> APER (Aligned PER) conversion

    Purpose: Convert BER data generated by Java to APER format,
    then send to network

    Args:
        ber_data: Bytes encoded in BER format

    Returns:
        Bytes encoded in APER format
    """
    assert req is not None
    req.from_ber(ber_data)
    return req.to_aper()


# ──────────────────────────────────────────────────────────────────────────────
# Test Examples
# ──────────────────────────────────────────────────────────────────────────────

def example1():
    """Example 1: Construct a Read-Request PDU with test data"""
    req.set_val((
        'confirmed-RequestPDU',
        {
            'invokeID': 123,
            'service': (
                'read',
                {
                    'variableAccessSpecification': (
                        'listOfVariable',
                        [{
                            'variableSpecification': (
                                'name',
                                ('domain-specific', {'domainID': 'TEST', 'itemID': 'VAL1'})
                            )
                        }]
                    )
                }
            )
        }
    ))


def example2():
    """Example 2: GetVariableAccessAttributes request"""
    req.set_val((
        'confirmed-RequestPDU',
        {
            'invokeID': 111,
            'service': (
                'getVariableAccessAttributes',
                ('name', ('domain-specific', {'domainID': 'TEST', 'itemID': 'VAL1'}))
            )
        }
    ))


def get_aper() -> bytes:
    """Get current PDU as APER bytes"""
    return req.to_aper()


def get_ber() -> bytes:
    """Get current PDU as BER bytes"""
    return req.to_ber()