# -*- coding: UTF-8 -*-
# Code automatically generated by pycrate_asn1c

from pycrate_asn1rt.utils            import *
from pycrate_asn1rt.err              import *
from pycrate_asn1rt.glob             import make_GLOBAL, GLOBAL
from pycrate_asn1rt.dictobj          import ASN1Dict
from pycrate_asn1rt.refobj           import *
from pycrate_asn1rt.setobj           import *
from pycrate_asn1rt.asnobj_basic     import *
from pycrate_asn1rt.asnobj_str       import *
from pycrate_asn1rt.asnobj_construct import *
from pycrate_asn1rt.asnobj_class     import *
from pycrate_asn1rt.asnobj_ext       import *
from pycrate_asn1rt.init             import init_modules

class ASN1:

    _name_  = 'ASN1'
    _oid_   = [1, 0, 9506, 2, 2]
    
    _obj_ = [
        'MMSpdu',
        'Confirmed-RequestPDU',
        'ConfirmedServiceRequest',
        'Unconfirmed-PDU',
        'UnconfirmedService',
        'Confirmed-ResponsePDU',
        'ConfirmedServiceResponse',
        'Confirmed-ErrorPDU',
        'ServiceError',
        'TimeOfDay',
        'BasicIdentifier',
        'Identifier',
        'Integer8',
        'Integer16',
        'Integer32',
        'Unsigned8',
        'Unsigned16',
        'Unsigned32',
        'ObjectName',
        'ObjectClass',
        'MMSString',
        'Initiate-RequestPDU',
        'Initiate-ResponsePDU',
        'Initiate-ErrorPDU',
        'Conclude-RequestPDU',
        'RejectPDU',
        'GetNameList-Request',
        'GetNameList-Response',
        'TypeSpecification',
        'AlternateAccess',
        'AlternateAccessSelection',
        'AccessResult',
        'Data',
        'FloatingPoint',
        'DataAccessError',
        'VariableAccessSpecification',
        'VariableDefs',
        'VariableSpecification',
        'Read-Request',
        'Read-Response',
        'Write-Request',
        'Write-Response',
        'InformationReport',
        'GetVariableAccessAttributes-Request',
        'GetVariableAccessAttributes-Response',
        'DefineNamedVariableList-Request',
        'DefineNamedVariableList-Response',
        'GetNamedVariableListAttributes-Request',
        'GetNamedVariableListAttributes-Response',
        'DeleteNamedVariableList-Request',
        'DeleteNamedVariableList-Response',
        'FileOpen-Request',
        'FileOpen-Response',
        'FileRead-Request',
        'FileRead-Response',
        'FileClose-Request',
        'FileClose-Response',
        'FileDelete-Request',
        'FileDelete-Response',
        'FileDirectory-Request',
        'FileDirectory-Response',
        'DirectoryEntry',
        'FileAttributes',
        'FileName',
        'TypeDescription',
        'UtcTime',
        'ParameterSupportOptions',
        'ServiceSupportOptions',
        ]
    _type_ = [
        'MMSpdu',
        'Confirmed-RequestPDU',
        'ConfirmedServiceRequest',
        'Unconfirmed-PDU',
        'UnconfirmedService',
        'Confirmed-ResponsePDU',
        'ConfirmedServiceResponse',
        'Confirmed-ErrorPDU',
        'ServiceError',
        'TimeOfDay',
        'BasicIdentifier',
        'Identifier',
        'Integer8',
        'Integer16',
        'Integer32',
        'Unsigned8',
        'Unsigned16',
        'Unsigned32',
        'ObjectName',
        'ObjectClass',
        'MMSString',
        'Initiate-RequestPDU',
        'Initiate-ResponsePDU',
        'Initiate-ErrorPDU',
        'Conclude-RequestPDU',
        'RejectPDU',
        'GetNameList-Request',
        'GetNameList-Response',
        'TypeSpecification',
        'AlternateAccess',
        'AlternateAccessSelection',
        'AccessResult',
        'Data',
        'FloatingPoint',
        'DataAccessError',
        'VariableAccessSpecification',
        'VariableDefs',
        'VariableSpecification',
        'Read-Request',
        'Read-Response',
        'Write-Request',
        'Write-Response',
        'InformationReport',
        'GetVariableAccessAttributes-Request',
        'GetVariableAccessAttributes-Response',
        'DefineNamedVariableList-Request',
        'DefineNamedVariableList-Response',
        'GetNamedVariableListAttributes-Request',
        'GetNamedVariableListAttributes-Response',
        'DeleteNamedVariableList-Request',
        'DeleteNamedVariableList-Response',
        'FileOpen-Request',
        'FileOpen-Response',
        'FileRead-Request',
        'FileRead-Response',
        'FileClose-Request',
        'FileClose-Response',
        'FileDelete-Request',
        'FileDelete-Response',
        'FileDirectory-Request',
        'FileDirectory-Response',
        'DirectoryEntry',
        'FileAttributes',
        'FileName',
        'TypeDescription',
        'UtcTime',
        'ParameterSupportOptions',
        'ServiceSupportOptions',
        'MMSpdu',
        'Confirmed-RequestPDU',
        'ConfirmedServiceRequest',
        'Unconfirmed-PDU',
        'UnconfirmedService',
        'Confirmed-ResponsePDU',
        'ConfirmedServiceResponse',
        'Confirmed-ErrorPDU',
        'ServiceError',
        'TimeOfDay',
        'BasicIdentifier',
        'Identifier',
        'Integer8',
        'Integer16',
        'Integer32',
        'Unsigned8',
        'Unsigned16',
        'Unsigned32',
        'ObjectName',
        'ObjectClass',
        'MMSString',
        'Initiate-RequestPDU',
        'Initiate-ResponsePDU',
        'Initiate-ErrorPDU',
        'Conclude-RequestPDU',
        'RejectPDU',
        'GetNameList-Request',
        'GetNameList-Response',
        'TypeSpecification',
        'AlternateAccess',
        'AlternateAccessSelection',
        'AccessResult',
        'Data',
        'FloatingPoint',
        'DataAccessError',
        'VariableAccessSpecification',
        'VariableDefs',
        'VariableSpecification',
        'Read-Request',
        'Read-Response',
        'Write-Request',
        'Write-Response',
        'InformationReport',
        'GetVariableAccessAttributes-Request',
        'GetVariableAccessAttributes-Response',
        'DefineNamedVariableList-Request',
        'DefineNamedVariableList-Response',
        'GetNamedVariableListAttributes-Request',
        'GetNamedVariableListAttributes-Response',
        'DeleteNamedVariableList-Request',
        'DeleteNamedVariableList-Response',
        'FileOpen-Request',
        'FileOpen-Response',
        'FileRead-Request',
        'FileRead-Response',
        'FileClose-Request',
        'FileClose-Response',
        'FileDelete-Request',
        'FileDelete-Response',
        'FileDirectory-Request',
        'FileDirectory-Response',
        'DirectoryEntry',
        'FileAttributes',
        'FileName',
        'TypeDescription',
        'UtcTime',
        'ParameterSupportOptions',
        'ServiceSupportOptions',
        ]
    _set_ = [
        ]
    _val_ = [
        ]
    _class_ = [
        ]
    _param_ = [
        ]
    
    #-----< MMSpdu >-----#
    MMSpdu = CHOICE(name='MMSpdu', mode=MODE_TYPE)
    _MMSpdu_confirmed_RequestPDU = SEQ(name='confirmed-RequestPDU', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Confirmed-RequestPDU')))
    _MMSpdu_confirmed_ResponsePDU = SEQ(name='confirmed-ResponsePDU', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Confirmed-ResponsePDU')))
    _MMSpdu_confirmed_ErrorPDU = SEQ(name='confirmed-ErrorPDU', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Confirmed-ErrorPDU')))
    _MMSpdu_unconfirmed_PDU = SEQ(name='unconfirmed-PDU', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Unconfirmed-PDU')))
    _MMSpdu_rejectPDU = SEQ(name='rejectPDU', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'RejectPDU')))
    _MMSpdu_initiate_RequestPDU = SEQ(name='initiate-RequestPDU', mode=MODE_TYPE, tag=(8, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Initiate-RequestPDU')))
    _MMSpdu_initiate_ResponsePDU = SEQ(name='initiate-ResponsePDU', mode=MODE_TYPE, tag=(9, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Initiate-ResponsePDU')))
    _MMSpdu_initiate_ErrorPDU = SEQ(name='initiate-ErrorPDU', mode=MODE_TYPE, tag=(10, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Initiate-ErrorPDU')))
    _MMSpdu_conclude_RequestPDU = NULL(name='conclude-RequestPDU', mode=MODE_TYPE, tag=(11, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Conclude-RequestPDU')))
    MMSpdu._cont = ASN1Dict([
        ('confirmed-RequestPDU', _MMSpdu_confirmed_RequestPDU),
        ('confirmed-ResponsePDU', _MMSpdu_confirmed_ResponsePDU),
        ('confirmed-ErrorPDU', _MMSpdu_confirmed_ErrorPDU),
        ('unconfirmed-PDU', _MMSpdu_unconfirmed_PDU),
        ('rejectPDU', _MMSpdu_rejectPDU),
        ('initiate-RequestPDU', _MMSpdu_initiate_RequestPDU),
        ('initiate-ResponsePDU', _MMSpdu_initiate_ResponsePDU),
        ('initiate-ErrorPDU', _MMSpdu_initiate_ErrorPDU),
        ('conclude-RequestPDU', _MMSpdu_conclude_RequestPDU),
        ])
    MMSpdu._ext = None
    
    #-----< Confirmed-RequestPDU >-----#
    Confirmed_RequestPDU = SEQ(name='Confirmed-RequestPDU', mode=MODE_TYPE)
    _Confirmed_RequestPDU_invokeID = INT(name='invokeID', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'Unsigned32')))
    _Confirmed_RequestPDU_service = CHOICE(name='service', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'ConfirmedServiceRequest')))
    Confirmed_RequestPDU._cont = ASN1Dict([
        ('invokeID', _Confirmed_RequestPDU_invokeID),
        ('service', _Confirmed_RequestPDU_service),
        ])
    Confirmed_RequestPDU._ext = None
    
    #-----< ConfirmedServiceRequest >-----#
    ConfirmedServiceRequest = CHOICE(name='ConfirmedServiceRequest', mode=MODE_TYPE)
    _ConfirmedServiceRequest_getNameList = SEQ(name='getNameList', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'GetNameList-Request')))
    _ConfirmedServiceRequest_read = SEQ(name='read', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Read-Request')))
    _ConfirmedServiceRequest_write = SEQ(name='write', mode=MODE_TYPE, tag=(5, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Write-Request')))
    _ConfirmedServiceRequest_getVariableAccessAttributes = CHOICE(name='getVariableAccessAttributes', mode=MODE_TYPE, tag=(6, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('ASN1', 'GetVariableAccessAttributes-Request')))
    _ConfirmedServiceRequest_defineNamedVariableList = SEQ(name='defineNamedVariableList', mode=MODE_TYPE, tag=(11, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'DefineNamedVariableList-Request')))
    _ConfirmedServiceRequest_getNamedVariableListAttributes = CHOICE(name='getNamedVariableListAttributes', mode=MODE_TYPE, tag=(12, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('ASN1', 'GetNamedVariableListAttributes-Request')))
    _ConfirmedServiceRequest_deleteNamedVariableList = SEQ(name='deleteNamedVariableList', mode=MODE_TYPE, tag=(13, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'DeleteNamedVariableList-Request')))
    _ConfirmedServiceRequest_fileOpen = SEQ(name='fileOpen', mode=MODE_TYPE, tag=(72, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'FileOpen-Request')))
    _ConfirmedServiceRequest_fileRead = INT(name='fileRead', mode=MODE_TYPE, tag=(73, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'FileRead-Request')))
    _ConfirmedServiceRequest_fileClose = INT(name='fileClose', mode=MODE_TYPE, tag=(74, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'FileClose-Request')))
    _ConfirmedServiceRequest_fileDelete = SEQ_OF(name='fileDelete', mode=MODE_TYPE, tag=(76, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'FileDelete-Request')))
    _ConfirmedServiceRequest_fileDirectory = SEQ(name='fileDirectory', mode=MODE_TYPE, tag=(77, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'FileDirectory-Request')))
    ConfirmedServiceRequest._cont = ASN1Dict([
        ('getNameList', _ConfirmedServiceRequest_getNameList),
        ('read', _ConfirmedServiceRequest_read),
        ('write', _ConfirmedServiceRequest_write),
        ('getVariableAccessAttributes', _ConfirmedServiceRequest_getVariableAccessAttributes),
        ('defineNamedVariableList', _ConfirmedServiceRequest_defineNamedVariableList),
        ('getNamedVariableListAttributes', _ConfirmedServiceRequest_getNamedVariableListAttributes),
        ('deleteNamedVariableList', _ConfirmedServiceRequest_deleteNamedVariableList),
        ('fileOpen', _ConfirmedServiceRequest_fileOpen),
        ('fileRead', _ConfirmedServiceRequest_fileRead),
        ('fileClose', _ConfirmedServiceRequest_fileClose),
        ('fileDelete', _ConfirmedServiceRequest_fileDelete),
        ('fileDirectory', _ConfirmedServiceRequest_fileDirectory),
        ])
    ConfirmedServiceRequest._ext = None
    
    #-----< Unconfirmed-PDU >-----#
    Unconfirmed_PDU = SEQ(name='Unconfirmed-PDU', mode=MODE_TYPE)
    _Unconfirmed_PDU_service = CHOICE(name='service', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'UnconfirmedService')))
    Unconfirmed_PDU._cont = ASN1Dict([
        ('service', _Unconfirmed_PDU_service),
        ])
    Unconfirmed_PDU._ext = None
    
    #-----< UnconfirmedService >-----#
    UnconfirmedService = CHOICE(name='UnconfirmedService', mode=MODE_TYPE)
    _UnconfirmedService_informationReport = SEQ(name='informationReport', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'InformationReport')))
    UnconfirmedService._cont = ASN1Dict([
        ('informationReport', _UnconfirmedService_informationReport),
        ])
    UnconfirmedService._ext = None
    
    #-----< Confirmed-ResponsePDU >-----#
    Confirmed_ResponsePDU = SEQ(name='Confirmed-ResponsePDU', mode=MODE_TYPE)
    _Confirmed_ResponsePDU_invokeID = INT(name='invokeID', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'Unsigned32')))
    _Confirmed_ResponsePDU_service = CHOICE(name='service', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'ConfirmedServiceResponse')))
    Confirmed_ResponsePDU._cont = ASN1Dict([
        ('invokeID', _Confirmed_ResponsePDU_invokeID),
        ('service', _Confirmed_ResponsePDU_service),
        ])
    Confirmed_ResponsePDU._ext = None
    
    #-----< ConfirmedServiceResponse >-----#
    ConfirmedServiceResponse = CHOICE(name='ConfirmedServiceResponse', mode=MODE_TYPE)
    _ConfirmedServiceResponse_getNameList = SEQ(name='getNameList', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'GetNameList-Response')))
    _ConfirmedServiceResponse_read = SEQ(name='read', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Read-Response')))
    _ConfirmedServiceResponse_write = SEQ_OF(name='write', mode=MODE_TYPE, tag=(5, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Write-Response')))
    _ConfirmedServiceResponse_getVariableAccessAttributes = SEQ(name='getVariableAccessAttributes', mode=MODE_TYPE, tag=(6, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'GetVariableAccessAttributes-Response')))
    _ConfirmedServiceResponse_defineNamedVariableList = NULL(name='defineNamedVariableList', mode=MODE_TYPE, tag=(11, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'DefineNamedVariableList-Response')))
    _ConfirmedServiceResponse_getNamedVariableListAttributes = SEQ(name='getNamedVariableListAttributes', mode=MODE_TYPE, tag=(12, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'GetNamedVariableListAttributes-Response')))
    _ConfirmedServiceResponse_deleteNamedVariableList = SEQ(name='deleteNamedVariableList', mode=MODE_TYPE, tag=(13, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'DeleteNamedVariableList-Response')))
    _ConfirmedServiceResponse_fileOpen = SEQ(name='fileOpen', mode=MODE_TYPE, tag=(72, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'FileOpen-Response')))
    _ConfirmedServiceResponse_fileRead = SEQ(name='fileRead', mode=MODE_TYPE, tag=(73, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'FileRead-Response')))
    _ConfirmedServiceResponse_fileClose = NULL(name='fileClose', mode=MODE_TYPE, tag=(74, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'FileClose-Response')))
    _ConfirmedServiceResponse_fileDelete = NULL(name='fileDelete', mode=MODE_TYPE, tag=(76, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'FileDelete-Response')))
    _ConfirmedServiceResponse_fileDirectory = SEQ(name='fileDirectory', mode=MODE_TYPE, tag=(77, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'FileDirectory-Response')))
    ConfirmedServiceResponse._cont = ASN1Dict([
        ('getNameList', _ConfirmedServiceResponse_getNameList),
        ('read', _ConfirmedServiceResponse_read),
        ('write', _ConfirmedServiceResponse_write),
        ('getVariableAccessAttributes', _ConfirmedServiceResponse_getVariableAccessAttributes),
        ('defineNamedVariableList', _ConfirmedServiceResponse_defineNamedVariableList),
        ('getNamedVariableListAttributes', _ConfirmedServiceResponse_getNamedVariableListAttributes),
        ('deleteNamedVariableList', _ConfirmedServiceResponse_deleteNamedVariableList),
        ('fileOpen', _ConfirmedServiceResponse_fileOpen),
        ('fileRead', _ConfirmedServiceResponse_fileRead),
        ('fileClose', _ConfirmedServiceResponse_fileClose),
        ('fileDelete', _ConfirmedServiceResponse_fileDelete),
        ('fileDirectory', _ConfirmedServiceResponse_fileDirectory),
        ])
    ConfirmedServiceResponse._ext = None
    
    #-----< Confirmed-ErrorPDU >-----#
    Confirmed_ErrorPDU = SEQ(name='Confirmed-ErrorPDU', mode=MODE_TYPE)
    _Confirmed_ErrorPDU_invokeID = INT(name='invokeID', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Unsigned32')))
    _Confirmed_ErrorPDU_modifierPosition = INT(name='modifierPosition', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Unsigned32')), opt=True)
    _Confirmed_ErrorPDU_serviceError = SEQ(name='serviceError', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'ServiceError')))
    Confirmed_ErrorPDU._cont = ASN1Dict([
        ('invokeID', _Confirmed_ErrorPDU_invokeID),
        ('modifierPosition', _Confirmed_ErrorPDU_modifierPosition),
        ('serviceError', _Confirmed_ErrorPDU_serviceError),
        ])
    Confirmed_ErrorPDU._ext = None
    
    #-----< ServiceError >-----#
    ServiceError = SEQ(name='ServiceError', mode=MODE_TYPE)
    _ServiceError_errorClass = CHOICE(name='errorClass', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_EXPLICIT))
    __ServiceError_errorClass_vmd_state = INT(name='vmd-state', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __ServiceError_errorClass_application_reference = INT(name='application-reference', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __ServiceError_errorClass_definition = INT(name='definition', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __ServiceError_errorClass_resource = INT(name='resource', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __ServiceError_errorClass_service = INT(name='service', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __ServiceError_errorClass_service_preempt = INT(name='service-preempt', mode=MODE_TYPE, tag=(5, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __ServiceError_errorClass_time_resolution = INT(name='time-resolution', mode=MODE_TYPE, tag=(6, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __ServiceError_errorClass_access = INT(name='access', mode=MODE_TYPE, tag=(7, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __ServiceError_errorClass_initiate = INT(name='initiate', mode=MODE_TYPE, tag=(8, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __ServiceError_errorClass_conclude = INT(name='conclude', mode=MODE_TYPE, tag=(9, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __ServiceError_errorClass_cancel = INT(name='cancel', mode=MODE_TYPE, tag=(10, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __ServiceError_errorClass_file = INT(name='file', mode=MODE_TYPE, tag=(11, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __ServiceError_errorClass_others = INT(name='others', mode=MODE_TYPE, tag=(12, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _ServiceError_errorClass._cont = ASN1Dict([
        ('vmd-state', __ServiceError_errorClass_vmd_state),
        ('application-reference', __ServiceError_errorClass_application_reference),
        ('definition', __ServiceError_errorClass_definition),
        ('resource', __ServiceError_errorClass_resource),
        ('service', __ServiceError_errorClass_service),
        ('service-preempt', __ServiceError_errorClass_service_preempt),
        ('time-resolution', __ServiceError_errorClass_time_resolution),
        ('access', __ServiceError_errorClass_access),
        ('initiate', __ServiceError_errorClass_initiate),
        ('conclude', __ServiceError_errorClass_conclude),
        ('cancel', __ServiceError_errorClass_cancel),
        ('file', __ServiceError_errorClass_file),
        ('others', __ServiceError_errorClass_others),
        ])
    _ServiceError_errorClass._ext = None
    _ServiceError_additionalCode = INT(name='additionalCode', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _ServiceError_additionalDescription = STR_VIS(name='additionalDescription', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    ServiceError._cont = ASN1Dict([
        ('errorClass', _ServiceError_errorClass),
        ('additionalCode', _ServiceError_additionalCode),
        ('additionalDescription', _ServiceError_additionalDescription),
        ])
    ServiceError._ext = None
    
    #-----< TimeOfDay >-----#
    TimeOfDay = OCT_STR(name='TimeOfDay', mode=MODE_TYPE)
    TimeOfDay._const_sz = ASN1Set(rv=[4, 6], rr=[], ev=None, er=[])
    
    #-----< BasicIdentifier >-----#
    BasicIdentifier = STR_VIS(name='BasicIdentifier', mode=MODE_TYPE)
    BasicIdentifier._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=1, ub=32)], ev=None, er=[])
    BasicIdentifier._const_alpha = ASN1Set(rv=['A', 'a', 'B', 'b', 'C', 'c', 'D', 'd', 'E', 'e', 'F', 'f', 'G', 'g', 'H', 'h', 'I', 'i', 'J', 'j', 'K', 'k', 'L', 'l', 'M', 'm', 'N', 'n', 'O', 'o', 'P', 'p', 'Q', 'q', 'R', 'r', 'S', 's', 'T', 't', 'U', 'u', 'V', 'v', 'W', 'w', 'X', 'x', 'Y', 'y', 'Z', 'z', '$', '_', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], rr=[], ev=None, er=[])
    
    #-----< Identifier >-----#
    Identifier = STR_VIS(name='Identifier', mode=MODE_TYPE)
    
    #-----< Integer8 >-----#
    Integer8 = INT(name='Integer8', mode=MODE_TYPE)
    Integer8._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=-128, ub=127)], ev=None, er=[])
    
    #-----< Integer16 >-----#
    Integer16 = INT(name='Integer16', mode=MODE_TYPE)
    Integer16._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=-32768, ub=32767)], ev=None, er=[])
    
    #-----< Integer32 >-----#
    Integer32 = INT(name='Integer32', mode=MODE_TYPE)
    Integer32._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=-2147483648, ub=2147483647)], ev=None, er=[])
    
    #-----< Unsigned8 >-----#
    Unsigned8 = INT(name='Unsigned8', mode=MODE_TYPE)
    Unsigned8._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=255)], ev=None, er=[])
    
    #-----< Unsigned16 >-----#
    Unsigned16 = INT(name='Unsigned16', mode=MODE_TYPE)
    Unsigned16._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=65535)], ev=None, er=[])
    
    #-----< Unsigned32 >-----#
    Unsigned32 = INT(name='Unsigned32', mode=MODE_TYPE)
    Unsigned32._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=4294967295)], ev=None, er=[])
    
    #-----< ObjectName >-----#
    ObjectName = CHOICE(name='ObjectName', mode=MODE_TYPE)
    _ObjectName_vmd_specific = STR_VIS(name='vmd-specific', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Identifier')))
    _ObjectName_domain_specific = SEQ(name='domain-specific', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __ObjectName_domain_specific_domainID = STR_VIS(name='domainID', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'Identifier')))
    __ObjectName_domain_specific_itemID = STR_VIS(name='itemID', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'Identifier')))
    _ObjectName_domain_specific._cont = ASN1Dict([
        ('domainID', __ObjectName_domain_specific_domainID),
        ('itemID', __ObjectName_domain_specific_itemID),
        ])
    _ObjectName_domain_specific._ext = None
    _ObjectName_aa_specific = STR_VIS(name='aa-specific', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Identifier')))
    ObjectName._cont = ASN1Dict([
        ('vmd-specific', _ObjectName_vmd_specific),
        ('domain-specific', _ObjectName_domain_specific),
        ('aa-specific', _ObjectName_aa_specific),
        ])
    ObjectName._ext = None
    
    #-----< ObjectClass >-----#
    ObjectClass = CHOICE(name='ObjectClass', mode=MODE_TYPE)
    _ObjectClass_basicObjectClass = INT(name='basicObjectClass', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    ObjectClass._cont = ASN1Dict([
        ('basicObjectClass', _ObjectClass_basicObjectClass),
        ])
    ObjectClass._ext = None
    
    #-----< MMSString >-----#
    MMSString = STR_VIS(name='MMSString', mode=MODE_TYPE)
    
    #-----< Initiate-RequestPDU >-----#
    Initiate_RequestPDU = SEQ(name='Initiate-RequestPDU', mode=MODE_TYPE)
    _Initiate_RequestPDU_localDetailCalling = INT(name='localDetailCalling', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Integer32')), opt=True)
    _Initiate_RequestPDU_proposedMaxServOutstandingCalling = INT(name='proposedMaxServOutstandingCalling', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Integer16')))
    _Initiate_RequestPDU_proposedMaxServOutstandingCalled = INT(name='proposedMaxServOutstandingCalled', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Integer16')))
    _Initiate_RequestPDU_proposedDataStructureNestingLevel = INT(name='proposedDataStructureNestingLevel', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Integer8')), opt=True)
    _Initiate_RequestPDU_initRequestDetail = SEQ(name='initRequestDetail', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __Initiate_RequestPDU_initRequestDetail_proposedVersionNumber = INT(name='proposedVersionNumber', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Integer16')))
    __Initiate_RequestPDU_initRequestDetail_proposedParameterCBB = BIT_STR(name='proposedParameterCBB', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'ParameterSupportOptions')))
    __Initiate_RequestPDU_initRequestDetail_servicesSupportedCalling = BIT_STR(name='servicesSupportedCalling', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'ServiceSupportOptions')))
    _Initiate_RequestPDU_initRequestDetail._cont = ASN1Dict([
        ('proposedVersionNumber', __Initiate_RequestPDU_initRequestDetail_proposedVersionNumber),
        ('proposedParameterCBB', __Initiate_RequestPDU_initRequestDetail_proposedParameterCBB),
        ('servicesSupportedCalling', __Initiate_RequestPDU_initRequestDetail_servicesSupportedCalling),
        ])
    _Initiate_RequestPDU_initRequestDetail._ext = None
    Initiate_RequestPDU._cont = ASN1Dict([
        ('localDetailCalling', _Initiate_RequestPDU_localDetailCalling),
        ('proposedMaxServOutstandingCalling', _Initiate_RequestPDU_proposedMaxServOutstandingCalling),
        ('proposedMaxServOutstandingCalled', _Initiate_RequestPDU_proposedMaxServOutstandingCalled),
        ('proposedDataStructureNestingLevel', _Initiate_RequestPDU_proposedDataStructureNestingLevel),
        ('initRequestDetail', _Initiate_RequestPDU_initRequestDetail),
        ])
    Initiate_RequestPDU._ext = None
    
    #-----< Initiate-ResponsePDU >-----#
    Initiate_ResponsePDU = SEQ(name='Initiate-ResponsePDU', mode=MODE_TYPE)
    _Initiate_ResponsePDU_localDetailCalled = INT(name='localDetailCalled', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Integer32')), opt=True)
    _Initiate_ResponsePDU_negotiatedMaxServOutstandingCalling = INT(name='negotiatedMaxServOutstandingCalling', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Integer16')))
    _Initiate_ResponsePDU_negotiatedMaxServOutstandingCalled = INT(name='negotiatedMaxServOutstandingCalled', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Integer16')))
    _Initiate_ResponsePDU_negotiatedDataStructureNestingLevel = INT(name='negotiatedDataStructureNestingLevel', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Integer8')), opt=True)
    _Initiate_ResponsePDU_initResponseDetail = SEQ(name='initResponseDetail', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __Initiate_ResponsePDU_initResponseDetail_negotiatedVersionNumber = INT(name='negotiatedVersionNumber', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Integer16')))
    __Initiate_ResponsePDU_initResponseDetail_negotiatedParameterCBB = BIT_STR(name='negotiatedParameterCBB', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'ParameterSupportOptions')))
    __Initiate_ResponsePDU_initResponseDetail_servicesSupportedCalled = BIT_STR(name='servicesSupportedCalled', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'ServiceSupportOptions')))
    _Initiate_ResponsePDU_initResponseDetail._cont = ASN1Dict([
        ('negotiatedVersionNumber', __Initiate_ResponsePDU_initResponseDetail_negotiatedVersionNumber),
        ('negotiatedParameterCBB', __Initiate_ResponsePDU_initResponseDetail_negotiatedParameterCBB),
        ('servicesSupportedCalled', __Initiate_ResponsePDU_initResponseDetail_servicesSupportedCalled),
        ])
    _Initiate_ResponsePDU_initResponseDetail._ext = None
    Initiate_ResponsePDU._cont = ASN1Dict([
        ('localDetailCalled', _Initiate_ResponsePDU_localDetailCalled),
        ('negotiatedMaxServOutstandingCalling', _Initiate_ResponsePDU_negotiatedMaxServOutstandingCalling),
        ('negotiatedMaxServOutstandingCalled', _Initiate_ResponsePDU_negotiatedMaxServOutstandingCalled),
        ('negotiatedDataStructureNestingLevel', _Initiate_ResponsePDU_negotiatedDataStructureNestingLevel),
        ('initResponseDetail', _Initiate_ResponsePDU_initResponseDetail),
        ])
    Initiate_ResponsePDU._ext = None
    
    #-----< Initiate-ErrorPDU >-----#
    Initiate_ErrorPDU = SEQ(name='Initiate-ErrorPDU', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'ServiceError')))
    
    #-----< Conclude-RequestPDU >-----#
    Conclude_RequestPDU = NULL(name='Conclude-RequestPDU', mode=MODE_TYPE)
    
    #-----< RejectPDU >-----#
    RejectPDU = SEQ(name='RejectPDU', mode=MODE_TYPE)
    _RejectPDU_originalInvokeID = INT(name='originalInvokeID', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Unsigned32')), opt=True)
    _RejectPDU_rejectReason = CHOICE(name='rejectReason', mode=MODE_TYPE)
    __RejectPDU_rejectReason_confirmed_requestPDU = INT(name='confirmed-requestPDU', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __RejectPDU_rejectReason_confirmed_responsePDU = INT(name='confirmed-responsePDU', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __RejectPDU_rejectReason_confirmed_errorPDU = INT(name='confirmed-errorPDU', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __RejectPDU_rejectReason_unconfirmedPDU = INT(name='unconfirmedPDU', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __RejectPDU_rejectReason_pdu_error = INT(name='pdu-error', mode=MODE_TYPE, tag=(5, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __RejectPDU_rejectReason_cancel_requestPDU = INT(name='cancel-requestPDU', mode=MODE_TYPE, tag=(6, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __RejectPDU_rejectReason_cancel_responsePDU = INT(name='cancel-responsePDU', mode=MODE_TYPE, tag=(7, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __RejectPDU_rejectReason_cancel_errorPDU = INT(name='cancel-errorPDU', mode=MODE_TYPE, tag=(8, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __RejectPDU_rejectReason_conclude_requestPDU = INT(name='conclude-requestPDU', mode=MODE_TYPE, tag=(9, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __RejectPDU_rejectReason_conclude_responsePDU = INT(name='conclude-responsePDU', mode=MODE_TYPE, tag=(10, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __RejectPDU_rejectReason_conclude_errorPDU = INT(name='conclude-errorPDU', mode=MODE_TYPE, tag=(11, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _RejectPDU_rejectReason._cont = ASN1Dict([
        ('confirmed-requestPDU', __RejectPDU_rejectReason_confirmed_requestPDU),
        ('confirmed-responsePDU', __RejectPDU_rejectReason_confirmed_responsePDU),
        ('confirmed-errorPDU', __RejectPDU_rejectReason_confirmed_errorPDU),
        ('unconfirmedPDU', __RejectPDU_rejectReason_unconfirmedPDU),
        ('pdu-error', __RejectPDU_rejectReason_pdu_error),
        ('cancel-requestPDU', __RejectPDU_rejectReason_cancel_requestPDU),
        ('cancel-responsePDU', __RejectPDU_rejectReason_cancel_responsePDU),
        ('cancel-errorPDU', __RejectPDU_rejectReason_cancel_errorPDU),
        ('conclude-requestPDU', __RejectPDU_rejectReason_conclude_requestPDU),
        ('conclude-responsePDU', __RejectPDU_rejectReason_conclude_responsePDU),
        ('conclude-errorPDU', __RejectPDU_rejectReason_conclude_errorPDU),
        ])
    _RejectPDU_rejectReason._ext = None
    RejectPDU._cont = ASN1Dict([
        ('originalInvokeID', _RejectPDU_originalInvokeID),
        ('rejectReason', _RejectPDU_rejectReason),
        ])
    RejectPDU._ext = None
    
    #-----< GetNameList-Request >-----#
    GetNameList_Request = SEQ(name='GetNameList-Request', mode=MODE_TYPE)
    _GetNameList_Request_objectClass = CHOICE(name='objectClass', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('ASN1', 'ObjectClass')))
    _GetNameList_Request_objectScope = CHOICE(name='objectScope', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_EXPLICIT))
    __GetNameList_Request_objectScope_vmdSpecific = NULL(name='vmdSpecific', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __GetNameList_Request_objectScope_domainSpecific = STR_VIS(name='domainSpecific', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Identifier')))
    __GetNameList_Request_objectScope_aaSpecific = NULL(name='aaSpecific', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _GetNameList_Request_objectScope._cont = ASN1Dict([
        ('vmdSpecific', __GetNameList_Request_objectScope_vmdSpecific),
        ('domainSpecific', __GetNameList_Request_objectScope_domainSpecific),
        ('aaSpecific', __GetNameList_Request_objectScope_aaSpecific),
        ])
    _GetNameList_Request_objectScope._ext = None
    _GetNameList_Request_continueAfter = STR_VIS(name='continueAfter', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Identifier')), opt=True)
    GetNameList_Request._cont = ASN1Dict([
        ('objectClass', _GetNameList_Request_objectClass),
        ('objectScope', _GetNameList_Request_objectScope),
        ('continueAfter', _GetNameList_Request_continueAfter),
        ])
    GetNameList_Request._ext = None
    
    #-----< GetNameList-Response >-----#
    GetNameList_Response = SEQ(name='GetNameList-Response', mode=MODE_TYPE)
    _GetNameList_Response_listOfIdentifier = SEQ_OF(name='listOfIdentifier', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __GetNameList_Response_listOfIdentifier__item_ = STR_VIS(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'Identifier')))
    _GetNameList_Response_listOfIdentifier._cont = __GetNameList_Response_listOfIdentifier__item_
    _GetNameList_Response_moreFollows = BOOL(name='moreFollows', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), default=True)
    GetNameList_Response._cont = ASN1Dict([
        ('listOfIdentifier', _GetNameList_Response_listOfIdentifier),
        ('moreFollows', _GetNameList_Response_moreFollows),
        ])
    GetNameList_Response._ext = None
    
    #-----< TypeSpecification >-----#
    TypeSpecification = CHOICE(name='TypeSpecification', mode=MODE_TYPE)
    _TypeSpecification_typeDescription = CHOICE(name='typeDescription', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'TypeDescription')))
    TypeSpecification._cont = ASN1Dict([
        ('typeDescription', _TypeSpecification_typeDescription),
        ])
    TypeSpecification._ext = None
    
    #-----< AlternateAccess >-----#
    AlternateAccess = SEQ_OF(name='AlternateAccess', mode=MODE_TYPE)
    _AlternateAccess__item_ = CHOICE(name='_item_', mode=MODE_TYPE)
    __AlternateAccess__item__unnamed = CHOICE(name='unnamed', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'AlternateAccessSelection')))
    _AlternateAccess__item_._cont = ASN1Dict([
        ('unnamed', __AlternateAccess__item__unnamed),
        ])
    _AlternateAccess__item_._ext = None
    AlternateAccess._cont = _AlternateAccess__item_
    
    #-----< AlternateAccessSelection >-----#
    AlternateAccessSelection = CHOICE(name='AlternateAccessSelection', mode=MODE_TYPE)
    _AlternateAccessSelection_selectAlternateAccess = SEQ(name='selectAlternateAccess', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __AlternateAccessSelection_selectAlternateAccess_accessSelection = CHOICE(name='accessSelection', mode=MODE_TYPE)
    ___AlternateAccessSelection_selectAlternateAccess_accessSelection_component = CHOICE(name='component', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_EXPLICIT))
    ____AlternateAccessSelection_selectAlternateAccess_accessSelection_component_basic = STR_VIS(name='basic', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'BasicIdentifier')))
    ____AlternateAccessSelection_selectAlternateAccess_accessSelection_component_basic._const_alpha = ASN1Set(rv=['A', 'a', 'B', 'b', 'C', 'c', 'D', 'd', 'E', 'e', 'F', 'f', 'G', 'g', 'H', 'h', 'I', 'i', 'J', 'j', 'K', 'k', 'L', 'l', 'M', 'm', 'N', 'n', 'O', 'o', 'P', 'p', 'Q', 'q', 'R', 'r', 'S', 's', 'T', 't', 'U', 'u', 'V', 'v', 'W', 'w', 'X', 'x', 'Y', 'y', 'Z', 'z', '$', '_', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], rr=[], ev=None, er=[])
    ___AlternateAccessSelection_selectAlternateAccess_accessSelection_component._cont = ASN1Dict([
        ('basic', ____AlternateAccessSelection_selectAlternateAccess_accessSelection_component_basic),
        ])
    ___AlternateAccessSelection_selectAlternateAccess_accessSelection_component._ext = None
    ___AlternateAccessSelection_selectAlternateAccess_accessSelection_index = INT(name='index', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Unsigned32')))
    ___AlternateAccessSelection_selectAlternateAccess_accessSelection_indexRange = SEQ(name='indexRange', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    ____AlternateAccessSelection_selectAlternateAccess_accessSelection_indexRange_lowIndex = INT(name='lowIndex', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Unsigned32')))
    ____AlternateAccessSelection_selectAlternateAccess_accessSelection_indexRange_numberOfElements = INT(name='numberOfElements', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Unsigned32')))
    ___AlternateAccessSelection_selectAlternateAccess_accessSelection_indexRange._cont = ASN1Dict([
        ('lowIndex', ____AlternateAccessSelection_selectAlternateAccess_accessSelection_indexRange_lowIndex),
        ('numberOfElements', ____AlternateAccessSelection_selectAlternateAccess_accessSelection_indexRange_numberOfElements),
        ])
    ___AlternateAccessSelection_selectAlternateAccess_accessSelection_indexRange._ext = None
    ___AlternateAccessSelection_selectAlternateAccess_accessSelection_allElements = NULL(name='allElements', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __AlternateAccessSelection_selectAlternateAccess_accessSelection._cont = ASN1Dict([
        ('component', ___AlternateAccessSelection_selectAlternateAccess_accessSelection_component),
        ('index', ___AlternateAccessSelection_selectAlternateAccess_accessSelection_index),
        ('indexRange', ___AlternateAccessSelection_selectAlternateAccess_accessSelection_indexRange),
        ('allElements', ___AlternateAccessSelection_selectAlternateAccess_accessSelection_allElements),
        ])
    __AlternateAccessSelection_selectAlternateAccess_accessSelection._ext = None
    __AlternateAccessSelection_selectAlternateAccess_alternateAccess = SEQ_OF(name='alternateAccess', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'AlternateAccess')))
    _AlternateAccessSelection_selectAlternateAccess._cont = ASN1Dict([
        ('accessSelection', __AlternateAccessSelection_selectAlternateAccess_accessSelection),
        ('alternateAccess', __AlternateAccessSelection_selectAlternateAccess_alternateAccess),
        ])
    _AlternateAccessSelection_selectAlternateAccess._ext = None
    _AlternateAccessSelection_selectAccess = CHOICE(name='selectAccess', mode=MODE_TYPE)
    __AlternateAccessSelection_selectAccess_component = CHOICE(name='component', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_EXPLICIT))
    ___AlternateAccessSelection_selectAccess_component_basic = STR_VIS(name='basic', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'BasicIdentifier')))
    ___AlternateAccessSelection_selectAccess_component_basic._const_alpha = ASN1Set(rv=['A', 'a', 'B', 'b', 'C', 'c', 'D', 'd', 'E', 'e', 'F', 'f', 'G', 'g', 'H', 'h', 'I', 'i', 'J', 'j', 'K', 'k', 'L', 'l', 'M', 'm', 'N', 'n', 'O', 'o', 'P', 'p', 'Q', 'q', 'R', 'r', 'S', 's', 'T', 't', 'U', 'u', 'V', 'v', 'W', 'w', 'X', 'x', 'Y', 'y', 'Z', 'z', '$', '_', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], rr=[], ev=None, er=[])
    __AlternateAccessSelection_selectAccess_component._cont = ASN1Dict([
        ('basic', ___AlternateAccessSelection_selectAccess_component_basic),
        ])
    __AlternateAccessSelection_selectAccess_component._ext = None
    __AlternateAccessSelection_selectAccess_index = INT(name='index', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Unsigned32')))
    __AlternateAccessSelection_selectAccess_indexRange = SEQ(name='indexRange', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    ___AlternateAccessSelection_selectAccess_indexRange_lowIndex = INT(name='lowIndex', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Unsigned32')))
    ___AlternateAccessSelection_selectAccess_indexRange_numberOfElements = INT(name='numberOfElements', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Unsigned32')))
    __AlternateAccessSelection_selectAccess_indexRange._cont = ASN1Dict([
        ('lowIndex', ___AlternateAccessSelection_selectAccess_indexRange_lowIndex),
        ('numberOfElements', ___AlternateAccessSelection_selectAccess_indexRange_numberOfElements),
        ])
    __AlternateAccessSelection_selectAccess_indexRange._ext = None
    __AlternateAccessSelection_selectAccess_allElements = NULL(name='allElements', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _AlternateAccessSelection_selectAccess._cont = ASN1Dict([
        ('component', __AlternateAccessSelection_selectAccess_component),
        ('index', __AlternateAccessSelection_selectAccess_index),
        ('indexRange', __AlternateAccessSelection_selectAccess_indexRange),
        ('allElements', __AlternateAccessSelection_selectAccess_allElements),
        ])
    _AlternateAccessSelection_selectAccess._ext = None
    AlternateAccessSelection._cont = ASN1Dict([
        ('selectAlternateAccess', _AlternateAccessSelection_selectAlternateAccess),
        ('selectAccess', _AlternateAccessSelection_selectAccess),
        ])
    AlternateAccessSelection._ext = None
    
    #-----< AccessResult >-----#
    AccessResult = CHOICE(name='AccessResult', mode=MODE_TYPE)
    _AccessResult_failure = INT(name='failure', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'DataAccessError')))
    _AccessResult_success = CHOICE(name='success', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'Data')))
    AccessResult._cont = ASN1Dict([
        ('failure', _AccessResult_failure),
        ('success', _AccessResult_success),
        ])
    AccessResult._ext = None
    
    #-----< Data >-----#
    Data = CHOICE(name='Data', mode=MODE_TYPE)
    _Data_array = SEQ_OF(name='array', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __Data_array__item_ = CHOICE(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'Data')))
    _Data_array._cont = __Data_array__item_
    _Data_structure = SEQ_OF(name='structure', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __Data_structure__item_ = CHOICE(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'Data')))
    _Data_structure._cont = __Data_structure__item_
    _Data_bool = BOOL(name='bool', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Data_bit_string = BIT_STR(name='bit-string', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Data_integer = INT(name='integer', mode=MODE_TYPE, tag=(5, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Data_unsigned = INT(name='unsigned', mode=MODE_TYPE, tag=(6, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Data_floating_point = OCT_STR(name='floating-point', mode=MODE_TYPE, tag=(7, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'FloatingPoint')))
    _Data_octet_string = OCT_STR(name='octet-string', mode=MODE_TYPE, tag=(9, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Data_visible_string = STR_VIS(name='visible-string', mode=MODE_TYPE, tag=(10, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Data_binary_time = OCT_STR(name='binary-time', mode=MODE_TYPE, tag=(12, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'TimeOfDay')))
    _Data_mMSString = STR_VIS(name='mMSString', mode=MODE_TYPE, tag=(16, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'MMSString')))
    _Data_utc_time = OCT_STR(name='utc-time', mode=MODE_TYPE, tag=(17, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'UtcTime')))
    Data._cont = ASN1Dict([
        ('array', _Data_array),
        ('structure', _Data_structure),
        ('bool', _Data_bool),
        ('bit-string', _Data_bit_string),
        ('integer', _Data_integer),
        ('unsigned', _Data_unsigned),
        ('floating-point', _Data_floating_point),
        ('octet-string', _Data_octet_string),
        ('visible-string', _Data_visible_string),
        ('binary-time', _Data_binary_time),
        ('mMSString', _Data_mMSString),
        ('utc-time', _Data_utc_time),
        ])
    Data._ext = None
    
    #-----< FloatingPoint >-----#
    FloatingPoint = OCT_STR(name='FloatingPoint', mode=MODE_TYPE)
    
    #-----< DataAccessError >-----#
    DataAccessError = INT(name='DataAccessError', mode=MODE_TYPE)
    
    #-----< VariableAccessSpecification >-----#
    VariableAccessSpecification = CHOICE(name='VariableAccessSpecification', mode=MODE_TYPE)
    _VariableAccessSpecification_listOfVariable = SEQ_OF(name='listOfVariable', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'VariableDefs')))
    _VariableAccessSpecification_variableListName = CHOICE(name='variableListName', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('ASN1', 'ObjectName')))
    VariableAccessSpecification._cont = ASN1Dict([
        ('listOfVariable', _VariableAccessSpecification_listOfVariable),
        ('variableListName', _VariableAccessSpecification_variableListName),
        ])
    VariableAccessSpecification._ext = None
    
    #-----< VariableDefs >-----#
    VariableDefs = SEQ_OF(name='VariableDefs', mode=MODE_TYPE)
    _VariableDefs__item_ = SEQ(name='_item_', mode=MODE_TYPE)
    __VariableDefs__item__variableSpecification = CHOICE(name='variableSpecification', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'VariableSpecification')))
    __VariableDefs__item__alternateAccess = SEQ_OF(name='alternateAccess', mode=MODE_TYPE, tag=(5, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'AlternateAccess')), opt=True)
    _VariableDefs__item_._cont = ASN1Dict([
        ('variableSpecification', __VariableDefs__item__variableSpecification),
        ('alternateAccess', __VariableDefs__item__alternateAccess),
        ])
    _VariableDefs__item_._ext = None
    VariableDefs._cont = _VariableDefs__item_
    
    #-----< VariableSpecification >-----#
    VariableSpecification = CHOICE(name='VariableSpecification', mode=MODE_TYPE)
    _VariableSpecification_name = CHOICE(name='name', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('ASN1', 'ObjectName')))
    VariableSpecification._cont = ASN1Dict([
        ('name', _VariableSpecification_name),
        ])
    VariableSpecification._ext = None
    
    #-----< Read-Request >-----#
    Read_Request = SEQ(name='Read-Request', mode=MODE_TYPE)
    _Read_Request_specificationWithResult = BOOL(name='specificationWithResult', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), default=False)
    _Read_Request_variableAccessSpecification = CHOICE(name='variableAccessSpecification', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('ASN1', 'VariableAccessSpecification')))
    Read_Request._cont = ASN1Dict([
        ('specificationWithResult', _Read_Request_specificationWithResult),
        ('variableAccessSpecification', _Read_Request_variableAccessSpecification),
        ])
    Read_Request._ext = None
    
    #-----< Read-Response >-----#
    Read_Response = SEQ(name='Read-Response', mode=MODE_TYPE)
    _Read_Response_variableAccessSpecification = CHOICE(name='variableAccessSpecification', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('ASN1', 'VariableAccessSpecification')), opt=True)
    _Read_Response_listOfAccessResult = SEQ_OF(name='listOfAccessResult', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __Read_Response_listOfAccessResult__item_ = CHOICE(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'AccessResult')))
    _Read_Response_listOfAccessResult._cont = __Read_Response_listOfAccessResult__item_
    Read_Response._cont = ASN1Dict([
        ('variableAccessSpecification', _Read_Response_variableAccessSpecification),
        ('listOfAccessResult', _Read_Response_listOfAccessResult),
        ])
    Read_Response._ext = None
    
    #-----< Write-Request >-----#
    Write_Request = SEQ(name='Write-Request', mode=MODE_TYPE)
    _Write_Request_variableAccessSpecification = CHOICE(name='variableAccessSpecification', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'VariableAccessSpecification')))
    _Write_Request_listOfData = SEQ_OF(name='listOfData', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __Write_Request_listOfData__item_ = CHOICE(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'Data')))
    _Write_Request_listOfData._cont = __Write_Request_listOfData__item_
    Write_Request._cont = ASN1Dict([
        ('variableAccessSpecification', _Write_Request_variableAccessSpecification),
        ('listOfData', _Write_Request_listOfData),
        ])
    Write_Request._ext = None
    
    #-----< Write-Response >-----#
    Write_Response = SEQ_OF(name='Write-Response', mode=MODE_TYPE)
    _Write_Response__item_ = CHOICE(name='_item_', mode=MODE_TYPE)
    __Write_Response__item__failure = INT(name='failure', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'DataAccessError')))
    __Write_Response__item__success = NULL(name='success', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Write_Response__item_._cont = ASN1Dict([
        ('failure', __Write_Response__item__failure),
        ('success', __Write_Response__item__success),
        ])
    _Write_Response__item_._ext = None
    Write_Response._cont = _Write_Response__item_
    
    #-----< InformationReport >-----#
    InformationReport = SEQ(name='InformationReport', mode=MODE_TYPE)
    _InformationReport_variableAccessSpecification = CHOICE(name='variableAccessSpecification', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'VariableAccessSpecification')))
    _InformationReport_listOfAccessResult = SEQ_OF(name='listOfAccessResult', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __InformationReport_listOfAccessResult__item_ = CHOICE(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'AccessResult')))
    _InformationReport_listOfAccessResult._cont = __InformationReport_listOfAccessResult__item_
    InformationReport._cont = ASN1Dict([
        ('variableAccessSpecification', _InformationReport_variableAccessSpecification),
        ('listOfAccessResult', _InformationReport_listOfAccessResult),
        ])
    InformationReport._ext = None
    
    #-----< GetVariableAccessAttributes-Request >-----#
    GetVariableAccessAttributes_Request = CHOICE(name='GetVariableAccessAttributes-Request', mode=MODE_TYPE)
    _GetVariableAccessAttributes_Request_name = CHOICE(name='name', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('ASN1', 'ObjectName')))
    GetVariableAccessAttributes_Request._cont = ASN1Dict([
        ('name', _GetVariableAccessAttributes_Request_name),
        ])
    GetVariableAccessAttributes_Request._ext = None
    
    #-----< GetVariableAccessAttributes-Response >-----#
    GetVariableAccessAttributes_Response = SEQ(name='GetVariableAccessAttributes-Response', mode=MODE_TYPE)
    _GetVariableAccessAttributes_Response_mmsDeletable = BOOL(name='mmsDeletable', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _GetVariableAccessAttributes_Response_typeDescription = CHOICE(name='typeDescription', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('ASN1', 'TypeDescription')))
    GetVariableAccessAttributes_Response._cont = ASN1Dict([
        ('mmsDeletable', _GetVariableAccessAttributes_Response_mmsDeletable),
        ('typeDescription', _GetVariableAccessAttributes_Response_typeDescription),
        ])
    GetVariableAccessAttributes_Response._ext = None
    
    #-----< DefineNamedVariableList-Request >-----#
    DefineNamedVariableList_Request = SEQ(name='DefineNamedVariableList-Request', mode=MODE_TYPE)
    _DefineNamedVariableList_Request_variableListName = CHOICE(name='variableListName', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'ObjectName')))
    _DefineNamedVariableList_Request_listOfVariable = SEQ_OF(name='listOfVariable', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'VariableDefs')))
    DefineNamedVariableList_Request._cont = ASN1Dict([
        ('variableListName', _DefineNamedVariableList_Request_variableListName),
        ('listOfVariable', _DefineNamedVariableList_Request_listOfVariable),
        ])
    DefineNamedVariableList_Request._ext = None
    
    #-----< DefineNamedVariableList-Response >-----#
    DefineNamedVariableList_Response = NULL(name='DefineNamedVariableList-Response', mode=MODE_TYPE)
    
    #-----< GetNamedVariableListAttributes-Request >-----#
    GetNamedVariableListAttributes_Request = CHOICE(name='GetNamedVariableListAttributes-Request', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'ObjectName')))
    
    #-----< GetNamedVariableListAttributes-Response >-----#
    GetNamedVariableListAttributes_Response = SEQ(name='GetNamedVariableListAttributes-Response', mode=MODE_TYPE)
    _GetNamedVariableListAttributes_Response_mmsDeletable = BOOL(name='mmsDeletable', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _GetNamedVariableListAttributes_Response_listOfVariable = SEQ_OF(name='listOfVariable', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'VariableDefs')))
    GetNamedVariableListAttributes_Response._cont = ASN1Dict([
        ('mmsDeletable', _GetNamedVariableListAttributes_Response_mmsDeletable),
        ('listOfVariable', _GetNamedVariableListAttributes_Response_listOfVariable),
        ])
    GetNamedVariableListAttributes_Response._ext = None
    
    #-----< DeleteNamedVariableList-Request >-----#
    DeleteNamedVariableList_Request = SEQ(name='DeleteNamedVariableList-Request', mode=MODE_TYPE)
    _DeleteNamedVariableList_Request_scopeOfDelete = INT(name='scopeOfDelete', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), default=0)
    _DeleteNamedVariableList_Request_listOfVariableListName = SEQ_OF(name='listOfVariableListName', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    __DeleteNamedVariableList_Request_listOfVariableListName__item_ = CHOICE(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'ObjectName')))
    _DeleteNamedVariableList_Request_listOfVariableListName._cont = __DeleteNamedVariableList_Request_listOfVariableListName__item_
    _DeleteNamedVariableList_Request_domainName = CHOICE(name='domainName', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_EXPLICIT), opt=True)
    __DeleteNamedVariableList_Request_domainName_basic = STR_VIS(name='basic', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'BasicIdentifier')))
    __DeleteNamedVariableList_Request_domainName_basic._const_alpha = ASN1Set(rv=['A', 'a', 'B', 'b', 'C', 'c', 'D', 'd', 'E', 'e', 'F', 'f', 'G', 'g', 'H', 'h', 'I', 'i', 'J', 'j', 'K', 'k', 'L', 'l', 'M', 'm', 'N', 'n', 'O', 'o', 'P', 'p', 'Q', 'q', 'R', 'r', 'S', 's', 'T', 't', 'U', 'u', 'V', 'v', 'W', 'w', 'X', 'x', 'Y', 'y', 'Z', 'z', '$', '_', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], rr=[], ev=None, er=[])
    _DeleteNamedVariableList_Request_domainName._cont = ASN1Dict([
        ('basic', __DeleteNamedVariableList_Request_domainName_basic),
        ])
    _DeleteNamedVariableList_Request_domainName._ext = None
    DeleteNamedVariableList_Request._cont = ASN1Dict([
        ('scopeOfDelete', _DeleteNamedVariableList_Request_scopeOfDelete),
        ('listOfVariableListName', _DeleteNamedVariableList_Request_listOfVariableListName),
        ('domainName', _DeleteNamedVariableList_Request_domainName),
        ])
    DeleteNamedVariableList_Request._ext = None
    
    #-----< DeleteNamedVariableList-Response >-----#
    DeleteNamedVariableList_Response = SEQ(name='DeleteNamedVariableList-Response', mode=MODE_TYPE)
    _DeleteNamedVariableList_Response_numberMatched = INT(name='numberMatched', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Unsigned32')))
    _DeleteNamedVariableList_Response_numberDeleted = INT(name='numberDeleted', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Unsigned32')))
    DeleteNamedVariableList_Response._cont = ASN1Dict([
        ('numberMatched', _DeleteNamedVariableList_Response_numberMatched),
        ('numberDeleted', _DeleteNamedVariableList_Response_numberDeleted),
        ])
    DeleteNamedVariableList_Response._ext = None
    
    #-----< FileOpen-Request >-----#
    FileOpen_Request = SEQ(name='FileOpen-Request', mode=MODE_TYPE)
    _FileOpen_Request_fileName = SEQ_OF(name='fileName', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'FileName')))
    _FileOpen_Request_initialPosition = INT(name='initialPosition', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Unsigned32')))
    FileOpen_Request._cont = ASN1Dict([
        ('fileName', _FileOpen_Request_fileName),
        ('initialPosition', _FileOpen_Request_initialPosition),
        ])
    FileOpen_Request._ext = None
    
    #-----< FileOpen-Response >-----#
    FileOpen_Response = SEQ(name='FileOpen-Response', mode=MODE_TYPE)
    _FileOpen_Response_frsmID = INT(name='frsmID', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Integer32')))
    _FileOpen_Response_fileAttributes = SEQ(name='fileAttributes', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'FileAttributes')))
    FileOpen_Response._cont = ASN1Dict([
        ('frsmID', _FileOpen_Response_frsmID),
        ('fileAttributes', _FileOpen_Response_fileAttributes),
        ])
    FileOpen_Response._ext = None
    
    #-----< FileRead-Request >-----#
    FileRead_Request = INT(name='FileRead-Request', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'Integer32')))
    
    #-----< FileRead-Response >-----#
    FileRead_Response = SEQ(name='FileRead-Response', mode=MODE_TYPE)
    _FileRead_Response_fileData = OCT_STR(name='fileData', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _FileRead_Response_moreFollows = BOOL(name='moreFollows', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), default=True)
    FileRead_Response._cont = ASN1Dict([
        ('fileData', _FileRead_Response_fileData),
        ('moreFollows', _FileRead_Response_moreFollows),
        ])
    FileRead_Response._ext = None
    
    #-----< FileClose-Request >-----#
    FileClose_Request = INT(name='FileClose-Request', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'Integer32')))
    
    #-----< FileClose-Response >-----#
    FileClose_Response = NULL(name='FileClose-Response', mode=MODE_TYPE)
    
    #-----< FileDelete-Request >-----#
    FileDelete_Request = SEQ_OF(name='FileDelete-Request', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'FileName')))
    
    #-----< FileDelete-Response >-----#
    FileDelete_Response = NULL(name='FileDelete-Response', mode=MODE_TYPE)
    
    #-----< FileDirectory-Request >-----#
    FileDirectory_Request = SEQ(name='FileDirectory-Request', mode=MODE_TYPE)
    _FileDirectory_Request_fileSpecification = SEQ_OF(name='fileSpecification', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'FileName')), opt=True)
    _FileDirectory_Request_continueAfter = SEQ_OF(name='continueAfter', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'FileName')), opt=True)
    FileDirectory_Request._cont = ASN1Dict([
        ('fileSpecification', _FileDirectory_Request_fileSpecification),
        ('continueAfter', _FileDirectory_Request_continueAfter),
        ])
    FileDirectory_Request._ext = None
    
    #-----< FileDirectory-Response >-----#
    FileDirectory_Response = SEQ(name='FileDirectory-Response', mode=MODE_TYPE)
    _FileDirectory_Response_listOfDirectoryEntry = SEQ_OF(name='listOfDirectoryEntry', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_EXPLICIT))
    __FileDirectory_Response_listOfDirectoryEntry__item_ = SEQ(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'DirectoryEntry')))
    _FileDirectory_Response_listOfDirectoryEntry._cont = __FileDirectory_Response_listOfDirectoryEntry__item_
    _FileDirectory_Response_moreFollows = BOOL(name='moreFollows', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), default=False)
    FileDirectory_Response._cont = ASN1Dict([
        ('listOfDirectoryEntry', _FileDirectory_Response_listOfDirectoryEntry),
        ('moreFollows', _FileDirectory_Response_moreFollows),
        ])
    FileDirectory_Response._ext = None
    
    #-----< DirectoryEntry >-----#
    DirectoryEntry = SEQ(name='DirectoryEntry', mode=MODE_TYPE)
    _DirectoryEntry_fileName = SEQ_OF(name='fileName', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'FileName')))
    _DirectoryEntry_fileAttributes = SEQ(name='fileAttributes', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'FileAttributes')))
    DirectoryEntry._cont = ASN1Dict([
        ('fileName', _DirectoryEntry_fileName),
        ('fileAttributes', _DirectoryEntry_fileAttributes),
        ])
    DirectoryEntry._ext = None
    
    #-----< FileAttributes >-----#
    FileAttributes = SEQ(name='FileAttributes', mode=MODE_TYPE)
    _FileAttributes_sizeOfFile = INT(name='sizeOfFile', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Unsigned32')))
    _FileAttributes_lastModified = TIME_GEN(name='lastModified', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    FileAttributes._cont = ASN1Dict([
        ('sizeOfFile', _FileAttributes_sizeOfFile),
        ('lastModified', _FileAttributes_lastModified),
        ])
    FileAttributes._ext = None
    
    #-----< FileName >-----#
    FileName = SEQ_OF(name='FileName', mode=MODE_TYPE)
    _FileName__item_ = STR_GRAPH(name='_item_', mode=MODE_TYPE)
    FileName._cont = _FileName__item_
    
    #-----< TypeDescription >-----#
    TypeDescription = CHOICE(name='TypeDescription', mode=MODE_TYPE)
    _TypeDescription_array = SEQ(name='array', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __TypeDescription_array_packed = BOOL(name='packed', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), default=False)
    __TypeDescription_array_numberOfElements = INT(name='numberOfElements', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Unsigned32')))
    __TypeDescription_array_elementType = CHOICE(name='elementType', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('ASN1', 'TypeSpecification')))
    _TypeDescription_array._cont = ASN1Dict([
        ('packed', __TypeDescription_array_packed),
        ('numberOfElements', __TypeDescription_array_numberOfElements),
        ('elementType', __TypeDescription_array_elementType),
        ])
    _TypeDescription_array._ext = None
    _TypeDescription_structure = SEQ(name='structure', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __TypeDescription_structure_packed = BOOL(name='packed', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), default=False)
    __TypeDescription_structure_components = SEQ_OF(name='components', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    ___TypeDescription_structure_components__item_ = SEQ(name='_item_', mode=MODE_TYPE)
    ____TypeDescription_structure_components__item__componentName = STR_VIS(name='componentName', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Identifier')), opt=True)
    ____TypeDescription_structure_components__item__componentType = CHOICE(name='componentType', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('ASN1', 'TypeSpecification')))
    ___TypeDescription_structure_components__item_._cont = ASN1Dict([
        ('componentName', ____TypeDescription_structure_components__item__componentName),
        ('componentType', ____TypeDescription_structure_components__item__componentType),
        ])
    ___TypeDescription_structure_components__item_._ext = None
    __TypeDescription_structure_components._cont = ___TypeDescription_structure_components__item_
    _TypeDescription_structure._cont = ASN1Dict([
        ('packed', __TypeDescription_structure_packed),
        ('components', __TypeDescription_structure_components),
        ])
    _TypeDescription_structure._ext = None
    _TypeDescription_bool = NULL(name='bool', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _TypeDescription_bit_string = INT(name='bit-string', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Integer32')))
    _TypeDescription_integer = INT(name='integer', mode=MODE_TYPE, tag=(5, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Unsigned8')))
    _TypeDescription_unsigned = INT(name='unsigned', mode=MODE_TYPE, tag=(6, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Unsigned8')))
    _TypeDescription_floating_point = SEQ(name='floating-point', mode=MODE_TYPE, tag=(7, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __TypeDescription_floating_point_format_width = INT(name='format-width', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'Unsigned8')))
    __TypeDescription_floating_point_exponent_width = INT(name='exponent-width', mode=MODE_TYPE, typeref=ASN1RefType(('ASN1', 'Unsigned8')))
    _TypeDescription_floating_point._cont = ASN1Dict([
        ('format-width', __TypeDescription_floating_point_format_width),
        ('exponent-width', __TypeDescription_floating_point_exponent_width),
        ])
    _TypeDescription_floating_point._ext = None
    _TypeDescription_octet_string = INT(name='octet-string', mode=MODE_TYPE, tag=(9, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Integer32')))
    _TypeDescription_visible_string = INT(name='visible-string', mode=MODE_TYPE, tag=(10, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Integer32')))
    _TypeDescription_binary_time = BOOL(name='binary-time', mode=MODE_TYPE, tag=(12, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _TypeDescription_mMSString = INT(name='mMSString', mode=MODE_TYPE, tag=(16, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('ASN1', 'Integer32')))
    _TypeDescription_utc_time = NULL(name='utc-time', mode=MODE_TYPE, tag=(17, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    TypeDescription._cont = ASN1Dict([
        ('array', _TypeDescription_array),
        ('structure', _TypeDescription_structure),
        ('bool', _TypeDescription_bool),
        ('bit-string', _TypeDescription_bit_string),
        ('integer', _TypeDescription_integer),
        ('unsigned', _TypeDescription_unsigned),
        ('floating-point', _TypeDescription_floating_point),
        ('octet-string', _TypeDescription_octet_string),
        ('visible-string', _TypeDescription_visible_string),
        ('binary-time', _TypeDescription_binary_time),
        ('mMSString', _TypeDescription_mMSString),
        ('utc-time', _TypeDescription_utc_time),
        ])
    TypeDescription._ext = None
    
    #-----< UtcTime >-----#
    UtcTime = OCT_STR(name='UtcTime', mode=MODE_TYPE)
    UtcTime._const_sz = ASN1Set(rv=[8], rr=[], ev=None, er=[])
    
    #-----< ParameterSupportOptions >-----#
    ParameterSupportOptions = BIT_STR(name='ParameterSupportOptions', mode=MODE_TYPE)
    
    #-----< ServiceSupportOptions >-----#
    ServiceSupportOptions = BIT_STR(name='ServiceSupportOptions', mode=MODE_TYPE)
    
    _all_ = [
        _MMSpdu_confirmed_RequestPDU,
        _MMSpdu_confirmed_ResponsePDU,
        _MMSpdu_confirmed_ErrorPDU,
        _MMSpdu_unconfirmed_PDU,
        _MMSpdu_rejectPDU,
        _MMSpdu_initiate_RequestPDU,
        _MMSpdu_initiate_ResponsePDU,
        _MMSpdu_initiate_ErrorPDU,
        _MMSpdu_conclude_RequestPDU,
        MMSpdu,
        _Confirmed_RequestPDU_invokeID,
        _Confirmed_RequestPDU_service,
        Confirmed_RequestPDU,
        _ConfirmedServiceRequest_getNameList,
        _ConfirmedServiceRequest_read,
        _ConfirmedServiceRequest_write,
        _ConfirmedServiceRequest_getVariableAccessAttributes,
        _ConfirmedServiceRequest_defineNamedVariableList,
        _ConfirmedServiceRequest_getNamedVariableListAttributes,
        _ConfirmedServiceRequest_deleteNamedVariableList,
        _ConfirmedServiceRequest_fileOpen,
        _ConfirmedServiceRequest_fileRead,
        _ConfirmedServiceRequest_fileClose,
        _ConfirmedServiceRequest_fileDelete,
        _ConfirmedServiceRequest_fileDirectory,
        ConfirmedServiceRequest,
        _Unconfirmed_PDU_service,
        Unconfirmed_PDU,
        _UnconfirmedService_informationReport,
        UnconfirmedService,
        _Confirmed_ResponsePDU_invokeID,
        _Confirmed_ResponsePDU_service,
        Confirmed_ResponsePDU,
        _ConfirmedServiceResponse_getNameList,
        _ConfirmedServiceResponse_read,
        _ConfirmedServiceResponse_write,
        _ConfirmedServiceResponse_getVariableAccessAttributes,
        _ConfirmedServiceResponse_defineNamedVariableList,
        _ConfirmedServiceResponse_getNamedVariableListAttributes,
        _ConfirmedServiceResponse_deleteNamedVariableList,
        _ConfirmedServiceResponse_fileOpen,
        _ConfirmedServiceResponse_fileRead,
        _ConfirmedServiceResponse_fileClose,
        _ConfirmedServiceResponse_fileDelete,
        _ConfirmedServiceResponse_fileDirectory,
        ConfirmedServiceResponse,
        _Confirmed_ErrorPDU_invokeID,
        _Confirmed_ErrorPDU_modifierPosition,
        _Confirmed_ErrorPDU_serviceError,
        Confirmed_ErrorPDU,
        __ServiceError_errorClass_vmd_state,
        __ServiceError_errorClass_application_reference,
        __ServiceError_errorClass_definition,
        __ServiceError_errorClass_resource,
        __ServiceError_errorClass_service,
        __ServiceError_errorClass_service_preempt,
        __ServiceError_errorClass_time_resolution,
        __ServiceError_errorClass_access,
        __ServiceError_errorClass_initiate,
        __ServiceError_errorClass_conclude,
        __ServiceError_errorClass_cancel,
        __ServiceError_errorClass_file,
        __ServiceError_errorClass_others,
        _ServiceError_errorClass,
        _ServiceError_additionalCode,
        _ServiceError_additionalDescription,
        ServiceError,
        TimeOfDay,
        BasicIdentifier,
        Identifier,
        Integer8,
        Integer16,
        Integer32,
        Unsigned8,
        Unsigned16,
        Unsigned32,
        _ObjectName_vmd_specific,
        __ObjectName_domain_specific_domainID,
        __ObjectName_domain_specific_itemID,
        _ObjectName_domain_specific,
        _ObjectName_aa_specific,
        ObjectName,
        _ObjectClass_basicObjectClass,
        ObjectClass,
        MMSString,
        _Initiate_RequestPDU_localDetailCalling,
        _Initiate_RequestPDU_proposedMaxServOutstandingCalling,
        _Initiate_RequestPDU_proposedMaxServOutstandingCalled,
        _Initiate_RequestPDU_proposedDataStructureNestingLevel,
        __Initiate_RequestPDU_initRequestDetail_proposedVersionNumber,
        __Initiate_RequestPDU_initRequestDetail_proposedParameterCBB,
        __Initiate_RequestPDU_initRequestDetail_servicesSupportedCalling,
        _Initiate_RequestPDU_initRequestDetail,
        Initiate_RequestPDU,
        _Initiate_ResponsePDU_localDetailCalled,
        _Initiate_ResponsePDU_negotiatedMaxServOutstandingCalling,
        _Initiate_ResponsePDU_negotiatedMaxServOutstandingCalled,
        _Initiate_ResponsePDU_negotiatedDataStructureNestingLevel,
        __Initiate_ResponsePDU_initResponseDetail_negotiatedVersionNumber,
        __Initiate_ResponsePDU_initResponseDetail_negotiatedParameterCBB,
        __Initiate_ResponsePDU_initResponseDetail_servicesSupportedCalled,
        _Initiate_ResponsePDU_initResponseDetail,
        Initiate_ResponsePDU,
        Initiate_ErrorPDU,
        Conclude_RequestPDU,
        _RejectPDU_originalInvokeID,
        __RejectPDU_rejectReason_confirmed_requestPDU,
        __RejectPDU_rejectReason_confirmed_responsePDU,
        __RejectPDU_rejectReason_confirmed_errorPDU,
        __RejectPDU_rejectReason_unconfirmedPDU,
        __RejectPDU_rejectReason_pdu_error,
        __RejectPDU_rejectReason_cancel_requestPDU,
        __RejectPDU_rejectReason_cancel_responsePDU,
        __RejectPDU_rejectReason_cancel_errorPDU,
        __RejectPDU_rejectReason_conclude_requestPDU,
        __RejectPDU_rejectReason_conclude_responsePDU,
        __RejectPDU_rejectReason_conclude_errorPDU,
        _RejectPDU_rejectReason,
        RejectPDU,
        _GetNameList_Request_objectClass,
        __GetNameList_Request_objectScope_vmdSpecific,
        __GetNameList_Request_objectScope_domainSpecific,
        __GetNameList_Request_objectScope_aaSpecific,
        _GetNameList_Request_objectScope,
        _GetNameList_Request_continueAfter,
        GetNameList_Request,
        __GetNameList_Response_listOfIdentifier__item_,
        _GetNameList_Response_listOfIdentifier,
        _GetNameList_Response_moreFollows,
        GetNameList_Response,
        _TypeSpecification_typeDescription,
        TypeSpecification,
        __AlternateAccess__item__unnamed,
        _AlternateAccess__item_,
        AlternateAccess,
        ____AlternateAccessSelection_selectAlternateAccess_accessSelection_component_basic,
        ___AlternateAccessSelection_selectAlternateAccess_accessSelection_component,
        ___AlternateAccessSelection_selectAlternateAccess_accessSelection_index,
        ____AlternateAccessSelection_selectAlternateAccess_accessSelection_indexRange_lowIndex,
        ____AlternateAccessSelection_selectAlternateAccess_accessSelection_indexRange_numberOfElements,
        ___AlternateAccessSelection_selectAlternateAccess_accessSelection_indexRange,
        ___AlternateAccessSelection_selectAlternateAccess_accessSelection_allElements,
        __AlternateAccessSelection_selectAlternateAccess_accessSelection,
        __AlternateAccessSelection_selectAlternateAccess_alternateAccess,
        _AlternateAccessSelection_selectAlternateAccess,
        ___AlternateAccessSelection_selectAccess_component_basic,
        __AlternateAccessSelection_selectAccess_component,
        __AlternateAccessSelection_selectAccess_index,
        ___AlternateAccessSelection_selectAccess_indexRange_lowIndex,
        ___AlternateAccessSelection_selectAccess_indexRange_numberOfElements,
        __AlternateAccessSelection_selectAccess_indexRange,
        __AlternateAccessSelection_selectAccess_allElements,
        _AlternateAccessSelection_selectAccess,
        AlternateAccessSelection,
        _AccessResult_failure,
        _AccessResult_success,
        AccessResult,
        __Data_array__item_,
        _Data_array,
        __Data_structure__item_,
        _Data_structure,
        _Data_bool,
        _Data_bit_string,
        _Data_integer,
        _Data_unsigned,
        _Data_floating_point,
        _Data_octet_string,
        _Data_visible_string,
        _Data_binary_time,
        _Data_mMSString,
        _Data_utc_time,
        Data,
        FloatingPoint,
        DataAccessError,
        _VariableAccessSpecification_listOfVariable,
        _VariableAccessSpecification_variableListName,
        VariableAccessSpecification,
        __VariableDefs__item__variableSpecification,
        __VariableDefs__item__alternateAccess,
        _VariableDefs__item_,
        VariableDefs,
        _VariableSpecification_name,
        VariableSpecification,
        _Read_Request_specificationWithResult,
        _Read_Request_variableAccessSpecification,
        Read_Request,
        _Read_Response_variableAccessSpecification,
        __Read_Response_listOfAccessResult__item_,
        _Read_Response_listOfAccessResult,
        Read_Response,
        _Write_Request_variableAccessSpecification,
        __Write_Request_listOfData__item_,
        _Write_Request_listOfData,
        Write_Request,
        __Write_Response__item__failure,
        __Write_Response__item__success,
        _Write_Response__item_,
        Write_Response,
        _InformationReport_variableAccessSpecification,
        __InformationReport_listOfAccessResult__item_,
        _InformationReport_listOfAccessResult,
        InformationReport,
        _GetVariableAccessAttributes_Request_name,
        GetVariableAccessAttributes_Request,
        _GetVariableAccessAttributes_Response_mmsDeletable,
        _GetVariableAccessAttributes_Response_typeDescription,
        GetVariableAccessAttributes_Response,
        _DefineNamedVariableList_Request_variableListName,
        _DefineNamedVariableList_Request_listOfVariable,
        DefineNamedVariableList_Request,
        DefineNamedVariableList_Response,
        GetNamedVariableListAttributes_Request,
        _GetNamedVariableListAttributes_Response_mmsDeletable,
        _GetNamedVariableListAttributes_Response_listOfVariable,
        GetNamedVariableListAttributes_Response,
        _DeleteNamedVariableList_Request_scopeOfDelete,
        __DeleteNamedVariableList_Request_listOfVariableListName__item_,
        _DeleteNamedVariableList_Request_listOfVariableListName,
        __DeleteNamedVariableList_Request_domainName_basic,
        _DeleteNamedVariableList_Request_domainName,
        DeleteNamedVariableList_Request,
        _DeleteNamedVariableList_Response_numberMatched,
        _DeleteNamedVariableList_Response_numberDeleted,
        DeleteNamedVariableList_Response,
        _FileOpen_Request_fileName,
        _FileOpen_Request_initialPosition,
        FileOpen_Request,
        _FileOpen_Response_frsmID,
        _FileOpen_Response_fileAttributes,
        FileOpen_Response,
        FileRead_Request,
        _FileRead_Response_fileData,
        _FileRead_Response_moreFollows,
        FileRead_Response,
        FileClose_Request,
        FileClose_Response,
        FileDelete_Request,
        FileDelete_Response,
        _FileDirectory_Request_fileSpecification,
        _FileDirectory_Request_continueAfter,
        FileDirectory_Request,
        __FileDirectory_Response_listOfDirectoryEntry__item_,
        _FileDirectory_Response_listOfDirectoryEntry,
        _FileDirectory_Response_moreFollows,
        FileDirectory_Response,
        _DirectoryEntry_fileName,
        _DirectoryEntry_fileAttributes,
        DirectoryEntry,
        _FileAttributes_sizeOfFile,
        _FileAttributes_lastModified,
        FileAttributes,
        _FileName__item_,
        FileName,
        __TypeDescription_array_packed,
        __TypeDescription_array_numberOfElements,
        __TypeDescription_array_elementType,
        _TypeDescription_array,
        __TypeDescription_structure_packed,
        ____TypeDescription_structure_components__item__componentName,
        ____TypeDescription_structure_components__item__componentType,
        ___TypeDescription_structure_components__item_,
        __TypeDescription_structure_components,
        _TypeDescription_structure,
        _TypeDescription_bool,
        _TypeDescription_bit_string,
        _TypeDescription_integer,
        _TypeDescription_unsigned,
        __TypeDescription_floating_point_format_width,
        __TypeDescription_floating_point_exponent_width,
        _TypeDescription_floating_point,
        _TypeDescription_octet_string,
        _TypeDescription_visible_string,
        _TypeDescription_binary_time,
        _TypeDescription_mMSString,
        _TypeDescription_utc_time,
        TypeDescription,
        UtcTime,
        ParameterSupportOptions,
        ServiceSupportOptions,
    ]

init_modules(ASN1)
